project:
  type: book

book:
  title: "le livre d'Amalia"
  author: "GranPiero"
  date: "4/17/2024"
  chapters:
    - index.qmd
    - prenoms.qmd
    - martine.qmd
    - design_and_features.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    pdf-engine: lualatex
    classoption: landscape

editor: visual

